---
title: "day0623"
output:
  html_document:
    keep_md: true
date: '2022-06-23'
---



## 제목 1
ㄴㄴㄴㄴ
### 소제목 1

## 제목 2
ㅁㅇㄹㅇㄹ

### 소제목 1-1

##복습
iris데이터,sepal.length,sepal.width 활용해서 종별로 산점도를 그리세요.
-제목과 x축, y축을 변경하세요
+x축 길이, y축 너비

```r
library(ggplot2)
summary(iris)
```

```
##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## 
```

```r
ggplot(iris, aes(x=Sepal.Length, y=Sepal.Width, col=Species))+
  geom_point()
```

![](/images/day0623/unnamed-chunk-1-1.png)<!-- -->

```r
library(ggplot2)

str(iris)
```

```
## 'data.frame':	150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
```

```r
ggplot(iris,aes(x=Sepal.Length,y=Sepal.Width, col=Species))+
  geom_point()+
  labs(
    title="제목",
    x="길이",
    y="너비"
  )+
  scale_color_manual(
    labels= c("setosa", "vericolor","virginica"),
    values= c("red","blue","yellow")
  )+
  theme_classic()
```

![](/images/day0623/unnamed-chunk-2-1.png)<!-- -->


#평균차이 검정
  -가설 검정: 평균의 차이를 검정
  -남자의 평균키와 여자의 평균 키는 차이가 있을 것이다. 
  
  #교차분석(=빈도분석)
-가설검정: 각 범주별 비도를 활용해서 관계성을 검정  
#단순 회귀 분석
  - y =ax + b
  - y는 종속변수, x가 정해져야지 정해진다.
  -온도 판매량
  -가설 검정
  + 기온(독립변수)이 판매량(종속변수)에 긍정적(부정적)영향을 주고 있을 것이다. 
  
평균차이 분석, 회귀분석


###가설
-Hypothesis
----> 공부 방법: 선행 연구, 해당분석 방법의 가설 설정 예시 존재
-연구: 내가 궁금한 것을 찾는 것
-귀무가설: 두 그룹간의 평균 차이가 없다.
-대립가설: 두 그룹간의 평균 차이가 있다.

100명 중 5명 여기서 5명을 유의수준
유의수준=>0.05이내면 대립가설을 지지해주기로 했다. 
예외가 있다.=> 예외가 있음을 인정하자

-가설 검정에서 인정하는 유의수준
5%, 1%, 0.1% 또는 10% 

-A후보 44%
-B후보 42%

이재명 vs 윤형선
-이재명

t.test
-어떻게 데이터를 입력하는지 확인
-p.value, 유의수준 0.65이상: 귀무가설, 0.05이내 --> 대립 가설


```r
mpg1<-read.csv("../data/mpg1.csv", stringsAsFactors =F)
library(ggplot2)
ggplot(mpg1,aes(x=trans,y=cty))+
  geom_boxplot()
```

![](/images/day0623/unnamed-chunk-3-1.png)<!-- -->
-t.test검정
+귀무가설: auto와 manual의 cty 평균은 차이가 없다.
 대립 가설:auto와 manual의 cty 평균은 차이가 있다.(보다 작으면)

```r
t.test(data=mpg1, cty~trans)
```

```
## 
## 	Welch Two Sample t-test
## 
## data:  cty by trans
## t = -4.5375, df = 132.32, p-value = 1.263e-05
## alternative hypothesis: true difference in means between group auto and group manual is not equal to 0
## 95 percent confidence interval:
##  -3.887311 -1.527033
## sample estimates:
##   mean in group auto mean in group manual 
##             15.96815             18.67532
```

```r
              #종속변수~독립변수
              #y(반응변수)x(설명변수)
```
 
-두 그룹의 평균 차이 검정
  +사전 필수 검증
  +등분산 검정
    +두 그룹간의 분산이 비슷하면 ==> t.test(모수 검정)
    +두 그룹간의 분산이 다르면, -->비모수 검정
  +등분산 검정
    +귀무가설: 두 그룹간의 분산이 비슷하다.
    +대립가설:ㅈㄹ

```r
var.test(data=mpg1,cty~trans)
```

```
## 
## 	F test to compare two variances
## 
## data:  cty by trans
## F = 0.73539, num df = 156, denom df = 76, p-value = 0.1101
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4912917 1.0719468
## sample estimates:
## ratio of variances 
##          0.7353887
```

```r
ggplot(mpg1, aes(x=cty,fill=trans))+
  geom_density(alpha=0.1)
```

![](/images/day0623/unnamed-chunk-6-1.png)<!-- -->
### 교차분석
-범주형 변수들이 관계가 있다는 것을 검정
-비율에 차이가 있는지 검정 
-교차분석 검정은 R의chisq.test() 함수로 진행
-귀무가설: trans에 따라 drv(4,f,r)의 (비율)차이가 없다.
-대립가설: trans에 따라 drv의 차이가 있다.

#빈도표 / 비율

```r
table(mpg1$trans, mpg1$drv)
```

```
##         
##           4  f  r
##   auto   75 65 17
##   manual 28 41  8
```
비율

```r
prop.table(table(mpg1$trans,mpg1$drv),1)
```

```
##         
##                  4         f         r
##   auto   0.4777070 0.4140127 0.1082803
##   manual 0.3636364 0.5324675 0.1038961
```
-auto 4륜 구동(4)인 47.8%
-manual 전륜구동(f) 53.2% 가장 많음
-실제로 통계적으로 봤을 때, 차이가 있는지 검정

    
    

```r
chisq.test(mpg1$trans,mpg1$drv)
```

```
## 
## 	Pearson's Chi-squared test
## 
## data:  mpg1$trans and mpg1$drv
## X-squared = 3.1368, df = 2, p-value = 0.2084
```
-차이가 없다.
