---
title: "day0624"
output:
  html_document:
    keep_md: true
date: '2022-06-24'
---


-통계 검정
  +평균 차이 검정: 수치 데이터 +범주 데이터(두 그룹)
    -세 그룹 이상
  +비율 차이 검정: 범주 데이터
  +상관 관계: 수치 데이터
  +회귀
  
-통계 검정 사전 준비
  +분석을 위한 데이터가 적절한지 검정
  +등분산 검정(두 평균 차이 검정을 하려고 할 때, 분산이 비슷한지 확인하는 것), 수치 데이터가 정규 분포를 이루는가(정규성 검정)
  
-귀무가설, 대립가설 적절하게 설정
  +서울의 평균 임금과 부산의 평균 임금이 차이가 있을 것이다.
  +선행 연구(논문을 찾아서 응용)
  
-테스트
  +t.test, chisq.test, cor.test
  +p.value
    -p.value>0.05 --> 귀무가설을 지지
    -p.value<0.05 --> 대립가설을 지지
    
##회귀의 중요성
-기초 통계 : 특정한 결과에 영향을 주는 주 요인이 뭐냐? 이걸 찾는 것이 회귀.
-회귀분석과 종류
  +1세대 회귀 방법론: 다항 회귀분석, 다중 회귀분석, 포아송 회귀분석
  +2세대 회귀 방법론: 구조 방정식
  
  
  
-귀무가설&대립가설 존재
  +귀무가설:x(=독립 변수)가 y(=종속 변수)에 영향을 주지 않는다.
  +대립가설:x(=독립 변수)가 y(=종속 변수)에 영향을 준다.
  
-lm(종속 변수 ~ 독립 변수,data)
  +p.value
  

```r
RA<-lm(data=mtcars,mpg~disp)
summary(RA)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10
```
  

-머신 러닝, 인공지능
  + 주 목적은 예측
  + y = ax + b
  
  
  
ANOVA (분산 분석)
식1: y=disp + var1 + var2 + var3
식2: y=disp + var1 + var2

컬럼 개수가 100개
-전진소거법, 후진소거법

R-squared : 결정계수= 설명력= 0~1
-1로 수렴할수록 설명력이 좋다

특정한 결과에 영향을 주는 주 요인이 뭐냐? 이걸 찾는 것이 회귀


```r
lm(data=mtcars,mpg~disp)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Coefficients:
## (Intercept)         disp  
##    29.59985     -0.04122
```

```r
lm(formula=mpg~disp,data=mtcars)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Coefficients:
## (Intercept)         disp  
##    29.59985     -0.04122
```


#p-value가 0.5보다 작으면 회귀모형이 적합하다고 해석
그렇지 않으면 회귀모형에 문제가 있는 것이므로 회귀분석 자체가 성립x


```r
lm(data= mtcars,mpg~disp+hp+wt)
```

```
## 
## Call:
## lm(formula = mpg ~ disp + hp + wt, data = mtcars)
## 
## Coefficients:
## (Intercept)         disp           hp           wt  
##   37.105505    -0.000937    -0.031157    -3.800891
```


```r
RA<-lm(data=mtcars,mpg~disp+hp+wt)
summary(RA)
```

```
## 
## Call:
## lm(formula = mpg ~ disp + hp + wt, data = mtcars)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.891 -1.640 -0.172  1.061  5.861 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 37.105505   2.110815  17.579  < 2e-16 ***
## disp        -0.000937   0.010350  -0.091  0.92851    
## hp          -0.031157   0.011436  -2.724  0.01097 *  
## wt          -3.800891   1.066191  -3.565  0.00133 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.639 on 28 degrees of freedom
## Multiple R-squared:  0.8268,	Adjusted R-squared:  0.8083 
## F-statistic: 44.57 on 3 and 28 DF,  p-value: 8.65e-11
```


```r
library(dplyr)
```

```
## 
## 다음의 패키지를 부착합니다: 'dplyr'
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

```r
library(ggplot2)
library(foreign)
```


```r
mental<-read.spss("../data/한국행정연구원_사회통합실태조사_데이터_2019.sav")
```

```
## re-encoding from CP51949
```

```r
class(mental)#객체 유형 확인인
```

```
## [1] "list"
```

```r
mental<-as.data.frame(mental)#데이터프레임으로 변환하기기
class(mental)
```

```
## [1] "data.frame"
```


```r
str(mental)#mental 의 구조조
```

```
## 'data.frame':	8000 obs. of  276 variables:
##  $ id      : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ ara     : Factor w/ 17 levels "서울","부산",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ wt1     : num  12216 12216 8455 7421 6474 ...
##  $ wt2     : num  2.58 2.58 1.79 1.57 1.37 ...
##  $ q1_1    : Factor w/ 12 levels "0점 전혀 행복하지 않았다",..: 8 6 7 5 7 8 8 8 7 5 ...
##  $ q1_2    : Factor w/ 12 levels "0점 전혀 하지 않았다",..: 5 5 5 4 4 4 6 6 4 6 ...
##  $ q1_3    : Factor w/ 12 levels "0점 전혀 우울하지 않았다",..: 6 4 6 5 4 5 5 7 5 5 ...
##  $ q1_4    : Factor w/ 12 levels "0점 전혀 만족하지 않는다",..: 5 5 5 4 7 5 6 6 5 5 ...
##  $ q1_5    : Factor w/ 12 levels "0점 전혀 가치 없다",..: 6 4 5 4 8 7 7 6 5 4 ...
##  $ q2_1    : Factor w/ 11 levels "0점 전혀 안전하지 않다",..: 5 6 7 5 7 8 6 7 6 6 ...
##  $ q2_2    : Factor w/ 11 levels "0점 전혀 안전하지 않다",..: 4 7 6 4 7 7 7 5 4 5 ...
##  $ q2_3    : Factor w/ 11 levels "0점 전혀 안전하지 않다",..: 4 7 6 5 7 5 6 4 4 6 ...
##  $ q3      : Factor w/ 11 levels "0점 전혀 자유롭지 않다",..: 4 6 4 3 8 6 6 5 4 5 ...
##  $ q4      : Factor w/ 12 levels "0점 매우 낮다",..: 4 6 5 4 6 7 6 4 4 6 ...
##  $ q5_1    : Factor w/ 5 levels "전혀 그렇지 않다",..: 3 3 2 3 3 3 2 2 2 2 ...
##  $ q5_2    : Factor w/ 5 levels "전혀 그렇지 않다",..: 2 3 3 2 2 3 3 2 1 2 ...
##  $ q5_2_1  : Factor w/ 5 levels "전혀 그렇지 않다",..: 2 3 2 3 2 3 2 2 2 2 ...
##  $ q5_2_2  : Factor w/ 5 levels "전혀 그렇지 않다",..: 2 4 2 2 2 2 2 2 1 2 ...
##  $ q5_3    : Factor w/ 5 levels "전혀 그렇지 않다",..: 3 3 3 3 3 3 2 2 1 2 ...
##  $ q5_4    : Factor w/ 5 levels "전혀 그렇지 않다",..: 2 3 2 2 3 2 2 1 1 1 ...
##  $ q6      : Factor w/ 11 levels "0점 전혀 만족하지 않는다",..: 7 7 6 6 7 8 7 5 7 4 ...
##  $ q7      : Factor w/ 11 levels "0점 매우 나빠질 것이다",..: 7 6 6 5 6 7 8 6 5 4 ...
##  $ q8      : Factor w/ 11 levels "0점 전혀 만족하지 않는다",..: 6 6 6 7 6 6 7 5 5 3 ...
##  $ q9      : Factor w/ 11 levels "0점 매우 나빠질 것이다",..: 5 6 5 7 6 6 7 5 5 3 ...
##  $ q10     : Factor w/ 11 levels "0점 전혀 만족하지 않는다",..: 6 9 7 8 7 9 7 6 5 6 ...
##  $ q11     : Factor w/ 11 levels "0점 매우 나빠질 것이다",..: 4 9 6 5 5 7 6 6 5 8 ...
##  $ q12     : Factor w/ 11 levels "북한은 우리의 적이다",..: 4 4 7 6 6 7 7 7 3 7 ...
##  $ q13     : Factor w/ 11 levels "성장이 더 중요하다",..: 4 5 6 5 7 6 6 6 3 5 ...
##  $ q14     : Factor w/ 11 levels "공동체의 이익이 더 중요하다",..: 4 4 6 4 7 7 7 6 3 5 ...
##  $ q15_1   : Factor w/ 4 levels "고도의 경제성장",..: 1 1 1 1 3 2 2 2 4 3 ...
##  $ q15_2   : Factor w/ 4 levels "고도의 경제성장",..: 2 3 4 4 2 1 1 4 1 4 ...
##  $ q16_1   : Factor w/ 4 levels "국가의 질서 유지",..: 2 2 2 2 1 2 2 2 4 2 ...
##  $ q16_2   : Factor w/ 4 levels "국가의 질서 유지",..: 3 4 4 3 4 3 3 4 1 3 ...
##  $ q17_1   : Factor w/ 4 levels "경제 안정","범죄와의 전쟁",..: 2 3 3 2 2 1 2 2 4 1 ...
##  $ q17_2   : Factor w/ 4 levels "경제 안정","범죄와의 전쟁",..: 4 2 1 3 3 4 3 3 2 4 ...
##  $ q18_1   : Factor w/ 4 levels "전혀 동의하지 않는다",..: 2 2 2 3 2 3 3 2 3 2 ...
##  $ q18_2   : Factor w/ 4 levels "전혀 동의하지 않는다",..: 2 3 3 2 3 2 3 3 2 3 ...
##  $ q18_3   : Factor w/ 4 levels "전혀 동의하지 않는다",..: 2 2 3 2 2 2 3 2 2 2 ...
##  $ q19_1   : Factor w/ 6 levels "소속된 적이 없다",..: 1 2 1 1 1 1 1 1 3 1 ...
##  $ q19_2   : Factor w/ 6 levels "소속된 적이 없다",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ q19_3   : Factor w/ 6 levels "소속된 적이 없다",..: 1 1 1 3 1 1 1 1 1 1 ...
##  $ q19_4   : Factor w/ 6 levels "소속된 적이 없다",..: 3 1 1 3 2 3 3 3 3 1 ...
##  $ q19_5   : Factor w/ 6 levels "소속된 적이 없다",..: 1 2 1 1 1 2 1 1 1 1 ...
##  $ q19_6   : Factor w/ 6 levels "소속된 적이 없다",..: 3 1 1 1 1 1 2 1 1 1 ...
##  $ q19_7   : Factor w/ 6 levels "소속된 적이 없다",..: 3 1 1 1 3 1 2 3 2 1 ...
##  $ q19_8   : Factor w/ 6 levels "소속된 적이 없다",..: 1 1 2 1 2 1 1 1 1 1 ...
##  $ q19_9   : Factor w/ 6 levels "소속된 적이 없다",..: 1 1 1 1 2 1 1 2 1 1 ...
##  $ q20_1   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 4 4 2 4 6 2 5 4 6 5 ...
##  $ q20_2   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 5 3 3 5 6 3 4 5 6 4 ...
##  $ q20_3   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 6 3 4 4 5 2 4 4 5 5 ...
##  $ q20_4   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 5 4 5 3 6 2 4 5 5 4 ...
##  $ q20_5   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 5 2 4 4 6 2 5 5 5 4 ...
##  $ q20_6   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 5 2 5 3 6 3 3 5 7 4 ...
##  $ q20_7   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 5 3 5 3 6 2 3 5 6 3 ...
##  $ q20_8   : Factor w/ 8 levels "1점 전혀 중요하지 않다",..: 5 3 5 3 7 2 3 5 6 3 ...
##  $ q21_1   : Factor w/ 5 levels "전혀 동의하지 않는다",..: 4 3 3 3 4 4 4 3 4 3 ...
##  $ q21_2   : Factor w/ 5 levels "전혀 동의하지 않는다",..: 3 3 2 3 3 4 4 4 3 2 ...
##  $ q21_3   : Factor w/ 5 levels "전혀 동의하지 않는다",..: 3 4 3 4 3 5 4 3 4 2 ...
##  $ q21_4   : Factor w/ 5 levels "전혀 동의하지 않는다",..: 3 3 2 3 3 4 4 3 3 2 ...
##  $ q22_1   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 3 1 3 1 3 1 3 4 2 ...
##  $ q22_2   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 2 2 3 1 3 1 2 4 2 ...
##  $ q22_3   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 3 2 3 3 3 3 3 4 3 ...
##  $ q22_4   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 3 1 2 1 3 3 3 4 2 ...
##  $ q22_5   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 3 3 3 1 3 3 3 4 2 ...
##  $ q22_6   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 4 3 3 1 3 3 4 4 3 ...
##  $ q22_7   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 2 3 3 1 3 2 3 4 2 ...
##  $ q22_8   : Factor w/ 4 levels "지난 1년 동안 한 적이 있다",..: 4 2 3 3 1 1 2 3 1 2 ...
##  $ q23     : Factor w/ 2 levels "참여했다","참여하지 않았다": 1 1 1 1 1 1 2 1 1 1 ...
##  $ q24     : Factor w/ 2 levels "참여했다","참여하지 않았다": 1 1 1 1 1 1 2 1 1 1 ...
##  $ q25     : Factor w/ 2 levels "참여했다","참여하지 않았다": 1 1 1 2 1 1 2 1 1 1 ...
##  $ q26     : Factor w/ 2 levels "있다","없다": 1 1 1 1 2 1 2 1 1 2 ...
##  $ q27     : Factor w/ 6 levels "매우 보수적",..: 1 2 2 3 4 4 3 1 2 3 ...
##  $ q28_1   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 2 3 2 1 3 3 3 3 3 1 ...
##  $ q28_2   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 2 3 3 2 2 3 3 3 2 1 ...
##  $ q28_3   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 2 3 2 2 3 2 4 2 2 1 ...
##  $ q28_4   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 2 3 2 2 2 1 3 2 2 1 ...
##  $ q29_1   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 3 2 2 3 2 2 2 1 4 3 ...
##  $ q29_2   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 3 3 3 2 2 1 2 1 3 2 ...
##  $ q29_3   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 3 3 2 2 3 1 2 1 3 2 ...
##  $ q29_4   : Factor w/ 4 levels "전혀 이루어지지 않고 있다",..: 3 3 2 2 3 1 2 1 3 2 ...
##  $ q30_1   : Factor w/ 5 levels "없다","1~2명",..: 2 3 2 3 2 2 2 2 2 1 ...
##  $ q30_1_1 : Factor w/ 7 levels "전화","우편",..: 4 4 4 4 4 4 4 4 4 NA ...
##  $ q30_1_2 : Factor w/ 6 levels "이메일","SNS(페이스북, 트위터, 인스타그램 등)",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ q30_2   : Factor w/ 7 levels "없다","1~2명",..: 3 4 3 3 4 2 2 3 4 2 ...
##  $ q30_2_1 : Factor w/ 7 levels "전화","우편",..: 1 4 4 4 3 4 1 4 1 5 ...
##  $ q30_2_2 : Factor w/ 6 levels "이메일","SNS(페이스북, 트위터, 인스타그램 등)",..: NA NA NA NA 1 NA NA NA NA NA ...
##  $ q31_1   : Factor w/ 5 levels "없다","1~2명",..: 4 3 1 3 3 2 1 4 3 3 ...
##  $ q31_2   : Factor w/ 5 levels "없다","1~2명",..: 3 2 1 2 3 2 1 3 2 2 ...
##  $ q31_3   : Factor w/ 5 levels "없다","1~2명",..: 4 3 1 2 3 2 1 4 2 2 ...
##  $ q32_1   : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 2 1 2 3 3 1 2 ...
##  $ q32_2   : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 1 1 2 3 3 1 2 ...
##  $ q32_3   : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 2 1 2 3 3 1 2 ...
##  $ q33     : Factor w/ 5 levels "전혀 믿을 수 없다",..: 2 3 2 2 3 2 2 3 3 3 ...
##  $ q34_1   : Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 3 3 2 2 4 2 2 2 4 3 ...
##  $ q34_2   : Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 2 3 2 3 3 2 2 3 3 2 ...
##  $ q34_3   : Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 2 2 2 3 2 2 1 2 3 3 ...
##  $ q34_4   : Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 2 2 2 2 1 1 2 2 2 2 ...
##  $ q34_5   : Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 2 2 2 2 2 1 2 2 2 2 ...
##  $ q35_1   : Factor w/ 4 levels "전혀 믿지 않는다",..: 3 3 2 2 2 2 1 2 3 3 ...
##   [list output truncated]
```

```r
#추출 변수(변수 설명, 척도 범위) : 영어 변수 이름
mental<-mental %>% 
  select(q32_2,q1_4,q32_1,q34_1, q52,d17,,d1,d2,ara) %>% 
  rename(suicide=q32_2,
         satisfaction=q1_4,
         loneliness=q32_1,
         family_belief=q34_1,
         wealth=q52,
         health=d17,
         sex=d1,
         age=d2,
         area=ara)
str(mental)
```

```
## 'data.frame':	8000 obs. of  9 variables:
##  $ suicide      : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 1 1 2 3 3 1 2 ...
##  $ satisfaction : Factor w/ 12 levels "0점 전혀 만족하지 않는다",..: 5 5 5 4 7 5 6 6 5 5 ...
##  $ loneliness   : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 2 1 2 3 3 1 2 ...
##  $ family_belief: Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 3 3 2 2 4 2 2 2 4 3 ...
##  $ wealth       : Factor w/ 11 levels "0점 전혀 안정적이지 않다",..: 4 7 6 6 7 7 6 5 4 6 ...
##  $ health       : Factor w/ 5 levels "매우 나쁘다",..: 4 3 4 4 4 4 4 4 4 4 ...
##  $ sex          : Factor w/ 2 levels "남성","여성": 2 2 1 2 1 2 2 1 2 1 ...
##  $ age          : Factor w/ 5 levels "19~29세","30대",..: 5 5 4 4 3 3 1 5 5 3 ...
##  $ area         : Factor w/ 17 levels "서울","부산",..: 1 1 1 1 1 1 1 1 1 1 ...
```

```r
mental$suicide <- as.integer(mental$suicide)
mental$satisfaction<- as.integer(mental$satisfaction)
mental$loneliness<-as.integer(mental$loneliness)
mental$family_belief<-as.integer(mental$family_belief)
mental$wealth <-as.integer(mental$wealth)
mental$health<-as.integer(mental$health)

table(mental$suicide)
```

```
## 
##    1    2    3    4 
## 5592 1862  479   67
```

```r
table(mental$health)
```

```
## 
##    1    2    3    4    5 
##   87  509 2413 3730 1261
```

```r
table(mental$satisfaction)
```

```
## 
##    1    2    3    4    5    6    7    8    9   10   11 
##   49   79  170  302  440 2053 1611 1761 1040  321  174
```
#sex, age, area의 유형을 범주형에서 문자형으로 변환



```r
mental$satisfaction<-mental$satisfaction-1
mental$wealth<-mental$wealth-1
```

#age 범주 이름 바꾸기

```r
mental$age<-ifelse(mental$age=="19~29세","20대",
                   ifelse(mental$age=="60~69","60대",mental$age))
```
#결측치, 이상치 확인하기

```r
summary(mental)
```

```
##     suicide       satisfaction      loneliness    family_belief  
##  Min.   :1.000   Min.   : 0.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:1.000   1st Qu.: 5.000   1st Qu.:1.000   1st Qu.:3.000  
##  Median :1.000   Median : 6.000   Median :2.000   Median :4.000  
##  Mean   :1.378   Mean   : 6.037   Mean   :1.795   Mean   :3.576  
##  3rd Qu.:2.000   3rd Qu.: 7.000   3rd Qu.:2.000   3rd Qu.:4.000  
##  Max.   :4.000   Max.   :10.000   Max.   :4.000   Max.   :4.000  
##                                                                  
##      wealth           health        sex           age                 area     
##  Min.   : 0.000   Min.   :1.000   남성:4011   Length:8000        경기   :1103  
##  1st Qu.: 4.000   1st Qu.:3.000   여성:3989   Class :character   서울   : 965  
##  Median : 5.000   Median :4.000               Mode  :character   부산   : 539  
##  Mean   : 4.985   Mean   :3.696                                  경남   : 527  
##  3rd Qu.: 6.000   3rd Qu.:4.000                                  인천   : 522  
##  Max.   :10.000   Max.   :5.000                                  경북   : 466  
##                                                                  (Other):3878
```

#성별 빈도분석

```r
mental %>% 
  group_by(sex) %>% 
  summarise(n=n()) %>% #sex 변수의 범주별 빈도 구하기
  mutate(total=sum(n),
         pct=round(n/total*100,1))
```

```
## # A tibble: 2 × 4
##   sex       n total   pct
##   <fct> <int> <int> <dbl>
## 1 남성   4011  8000  50.1
## 2 여성   3989  8000  49.9
```
#연령대별 빈도분석

```r
mental %>% 
  group_by(age) %>% 
  summarise(n=n()) %>% 
  mutate(total=sum(n),
         pct=round(n/total*100,1))
```

```
## # A tibble: 5 × 4
##   age       n total   pct
##   <chr> <int> <int> <dbl>
## 1 2      1516  8000  19  
## 2 20대   1542  8000  19.3
## 3 3      1769  8000  22.1
## 4 4      1821  8000  22.8
## 5 5      1352  8000  16.9
```
#성과 연령대의 교차 빈도 구하기

```r
table(mental$sex,mental$age)
```

```
##       
##          2 20대   3   4   5
##   남성 745  822 900 891 653
##   여성 771  720 869 930 699
```
#성과 연령대의 교차 백분율 구하기, 행별로 100%기준.소수점 한자리

```r
round(prop.table(table(mental$sex,mental$age),1)*100,1)
```

```
##       
##           2 20대    3    4    5
##   남성 18.6 20.5 22.4 22.2 16.3
##   여성 19.3 18.0 21.8 23.3 17.5
```
#교차분석 검정

```r
chisq.test(mental$sex,mental$age)
```

```
## 
## 	Pearson's Chi-squared test
## 
## data:  mental$sex and mental$age
## X-squared = 10.076, df = 4, p-value = 0.03916
```
#p<0.05이므로 연령대 분포 비율은 다소 차이가 있다.


#suicide, satisfaction, loneliness, family_belif, wealth,health 변수의 평균을 분석한다.

```r
mental %>% 
  summarise(m1=mean(suicide), m2=mean(satisfaction),m3=mean(loneliness),m4=mean(family_belief),m5=mean(wealth),m6=mean(health))
```

```
##         m1     m2    m3       m4       m5       m6
## 1 1.377625 6.0365 1.795 3.576375 4.985125 3.696125
```


#자살충동은 4점 척도에서 1.38 따라서 낮은 편
#삶의 만족도 6.04 보통보다 조금 위
#외로움 1.8으로 상대적으로 낮은 편
#가족신뢰도 높은편
#경제 안정도: 보통 바로 밑
#건강상태: 5점 척도에서 3.7으로 좋은 수준



#삶의 만족도와 외로움을 독립변수로 하고, 자살충동을 종속변수로 하는 다중회귀분석


```r
RA<-lm(data=mental,suicide~satisfaction+loneliness)
summary(RA)
```

```
## 
## Call:
## lm(formula = suicide ~ satisfaction + loneliness, data = mental)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.50517 -0.40228 -0.03487  0.17773  3.07029 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   1.035551   0.029823   34.72   <2e-16 ***
## satisfaction -0.052583   0.003614  -14.55   <2e-16 ***
## loneliness    0.367405   0.007987   46.00   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5451 on 7997 degrees of freedom
## Multiple R-squared:  0.2668,	Adjusted R-squared:  0.2666 
## F-statistic:  1455 on 2 and 7997 DF,  p-value: < 2.2e-16
```
#suicide = 1.035551-0.052583 X satisfaction + 0.367405 X loneliness

#삶의 만족도와 외로움의 상관관계


```r
cor.test(mental$satisfaction,mental$loneliness)
```

```
## 
## 	Pearson's product-moment correlation
## 
## data:  mental$satisfaction and mental$loneliness
## t = -25.374, df = 7998, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.2931116 -0.2525481
## sample estimates:
##        cor 
## -0.2729512
```

#가족 신뢰도, 경제안정도, 건강상태가 삶의 만족도와 외로움에 미치는 옇야

```r
RA<-lm(data=mental, satisfaction~family_belief+wealth+health)
summary(RA)
```

```
## 
## Call:
## lm(formula = satisfaction ~ family_belief + wealth + health, 
##     data = mental)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.8274 -0.9431 -0.0425  1.0569  6.1986 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    2.07613    0.13765   15.08   <2e-16 ***
## family_belief  0.36851    0.03196   11.53   <2e-16 ***
## wealth         0.26016    0.01089   23.88   <2e-16 ***
## health         0.36403    0.02206   16.50   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.627 on 7996 degrees of freedom
## Multiple R-squared:  0.1386,	Adjusted R-squared:  0.1383 
## F-statistic: 428.8 on 3 and 7996 DF,  p-value: < 2.2e-16
```

#3개의 독립 변수가 외로움에 미치는 영향

```r
RA<-lm(data=mental, loneliness~family_belief+wealth+health)
summary(RA)
```

```
## 
## Call:
## lm(formula = loneliness ~ family_belief + wealth + health, data = mental)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.24066 -0.64247  0.01863  0.43022  2.83959 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    3.652247   0.063109   57.87   <2e-16 ***
## family_belief -0.220274   0.014654  -15.03   <2e-16 ***
## wealth        -0.072686   0.004995  -14.55   <2e-16 ***
## health        -0.191313   0.010116  -18.91   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.746 on 7996 degrees of freedom
## Multiple R-squared:  0.1157,	Adjusted R-squared:  0.1154 
## F-statistic: 348.9 on 3 and 7996 DF,  p-value: < 2.2e-16
```
=>3개의 변수 모두 유의미하다.
loneliness = 3.652247 -0.220274 X family_belief - 0.072686 X wealth -0.191313 X health


# 성별로 삶의 만족도에서 차이가 있는가를 독립표본 t검정으로 확인


```r
t.test(data=mental,satisfaction~sex)
```

```
## 
## 	Welch Two Sample t-test
## 
## data:  satisfaction by sex
## t = -3.7719, df = 7997.6, p-value = 0.0001632
## alternative hypothesis: true difference in means between group 남성 and group 여성 is not equal to 0
## 95 percent confidence interval:
##  -0.22446298 -0.07094075
## sample estimates:
## mean in group 남성 mean in group 여성 
##           5.962852           6.110554
```
#유의수준이 0.001보다 작기 때문에 이 통계 결과는 유의미하다.
여성의 만족도가 남성보다 높다고 할 수 있다.

#연령대별 삶의 만족도 차이

```r
mental %>% 
  group_by(age) %>% 
  summarise(m=mean(satisfaction)) %>% 
  arrange(desc(m))
```

```
## # A tibble: 5 × 2
##   age       m
##   <chr> <dbl>
## 1 2      6.13
## 2 4      6.08
## 3 3      6.05
## 4 20대   6.04
## 5 5      5.84
```
#30대가 6.13으로 가장 높다. 


#지역별 삶의 만족도 분석과 그래프 그리기

```r
area_satisfaction<-mental %>% 
  group_by(area) %>% 
  summarise(m=mean(satisfaction)) %>% 
  arrange(desc(m))
```

```r
ggplot(data=area_satisfaction,aes(x=reorder(area,m),y=m))+
  geom_col()+
  ggtitle("지역별 만족도")+
  xlab("지역")+
  ylab("만족도")+
  coord_flip()
```

![](/images/day0624/unnamed-chunk-26-1.png)<!-- -->


